avex_g="Average criticality-experimental G-values"
#avex_sub_g="Average subcriticality-experimental G-values"
#avex_super_g="Average supercriticality-experimental G-values"
samplecov_z="Sample-covariance for criticality preactivation values"
theor_g="Theoretical G-values"
theor_g_main="Theoretical G-values, main term only"
ex_g="Experimental G-values"
layernum="Layer number (0-based number)"
values_g="G-metric values"
valueslogabs_g="G-metric logarithmic absolute values"
valueslog_g="G-metric logarithmic values"

avex_v="Average experimental V-values"
theor_v="Theoretical V-values"
values_v="V-metric values"
valueslog_v="V-metric logarithmic values"
